webapp/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

    /**  All layouts use css/styles.css from html5 boilerplate.
              All less files are compiled into the css folder(you can define the output folder in WinLess).
     */

    
    /**
     *      Semantic,responsive  layout with Semantic Grid
     *       http://semantic.gs/
     *       This layout needs  less/sg/layout.less ,less/sg/responsive_sg.less and less/bs/bootstrap.less
     *        Also less/bs/responsive.less if you use the  bootstrap navbar for navigation
     *       Bootstrap is still used for non-layout design,so you can exclude layout related code in bootstrap.less.
    */
   // public $layout='//layouts/grid_sg';


	/**
	 *This layout is used with Bootstrap non-semantic classes.
     * It uses    less/bs/bootstrap.less,less/bs/responsive.less and  less/responsive_custom.less,
	 */
    public $layout='//layouts/grid_bs';

    /**
	 *This layout is semantic with Bootstrap,it uses  layout mixins like .makeRow() and .makeColumn();
     * It uses    less/sem_layout.less and bootstrap.less(with all layout code optionally excluded),
     * The downside is that you have to code a custom responsive less or css file.The default bootstrap responsive.less
     *  file will not work,since it produces the non-semantic classes .span* which are not used in this semantic layout.
     *
	 */
     //   public $layout='//layouts/grid_bs_sem';

    
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0x3CB9C6,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
        
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','<strong>Message sent!   </strong>Thank you for contacting us. We will respond to you as soon as possible.');

               $this->refresh();

			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
                   Yii::app()->user->setFlash('success', '<strong>Sudah Masuk!</strong>');
				    $this->redirect(Yii::app()->user->returnUrl);
            }
		}
		// display the login form

        if( !empty($_POST['LoginForm'])){
        Yii::app()->user->setFlash('error', '<strong>Belum Masuk.</strong> Salah identitas.');
        }
		$this->render('login',array('model'=>$model));

	}
	
	public function actionRegister()
	{
		$model=new UserForm('register');

		// uncomment the following code to enable ajax-based validation
		
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form-register-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		

		if(isset($_POST['UserForm']))
		{
			$model->attributes=$_POST['UserForm'];
			if($model->validate())
			{
				$baru = new User;
				$baru->scenario = 'register';
				$baru->attributes = $_POST['UserForm'];
				$baru->peran = 'verifikasi';
				$baru->save();
					
				// Redirect
				Yii::app()->user->setFlash('pesan','Terima Kasih sudah mendaftar. Anda sudah didaftarkan.');
				$this->redirect(Yii::app()->homeUrl);
				return;
			}
		}
		$this->render('register',array('model'=>$model));
	}
	
	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	public function actionAbout()
	{
		$this->render('about');
	}
}

webapp/protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/grid_bs';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('updateMe'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','update','create'),
				'expression'=>'$user->peran=="admin"',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}
	public function actionUpdateMe()
	{
		$model=$this->loadModel(Yii::app()->user->id);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		$this->breadcrumbs=array(
			'Users'=>array('index'),
			$model->id=>array('view','id'=>$model->id),
			'Update',
		);
		$this->render('_formUpdate', array('model'=>$model)); 
	}
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

webapp/protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

webapp/protected/views/layouts/grid_bs.php
<?php $this->beginContent('//layouts/main'); ?>
    
	<nav id="main-nav" role="navigation">
        <!-- Bootstrap Navigation Bar Menu -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <!-- Be sure to leave the brand out there if you want it shown -->
                    <a class="brand" href="<?php echo Yii::app()->createUrl('/site/index');?>"></a>

                    <div class="nav-collapse">
						<?php $this->widget('zii.widgets.CMenu', array(
							  'items' => array(
								  array('label' => 'Home', 'url' => array('/site/index')),
								  array('label' => 'Tentang', 'url' => array('/site/about')),
								  array('label' => 'Contact', 'url' => array('/site/contact')),
								  array('label' => 'Dashbor', 'url' => array('/dashbor/'), 'visible' => !Yii::app()->user->isGuest),
								  array('label' => 'User', 'url' => array('/user/admin'), 'visible' => (Yii::app()->user->peran=='admin')),
								  //array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
								  //array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
							  ),
							  'htmlOptions' => array('class' => 'nav')
						 )); ?>
						<ul class="nav pull-right">
						  <?php if(Yii::app()->user->isGuest): ?>
							<li><a href="<?php echo Yii::app()->createUrl('/site/register');?>">Daftar</a></li>
						  <?php endif; ?>
						  <li class="divider-vertical"></li>
						  <?php if(Yii::app()->user->isGuest): ?>
									<?php //$this->widget('application.widgets.UserLogin'); ?>
									<?php CWidget::render('application.widgets.UserLogin');?>
						  <?php else: ?>
								<li><?php $this->widget('ext.VGGravatarWidget.VGGravatarWidget', 
									array('email' => Yii::app()->user->email,'size'=>60,'htmlOptions'=>array('alt'=>Yii::app()->user->name)));
								?></li>
								<ul class="nav">
								  <li class="dropdown">
									<a href="#" class="dropdown-toggle"
										  data-toggle="dropdown">										  
										  <?php echo Yii::app()->user->name; ?>
										  <b class="caret"></b>
									</a>
									<ul class="dropdown-menu">
										<li><a href="<?php echo Yii::app()->createUrl('/user/updateme');?>">Profil</a></li>
										<li><a href="<?php echo Yii::app()->createUrl('/site/logout');?>">Logout</a></li>
									</ul>
								  </li>
								</ul>
								
						  <?php endif; ?>
						</ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
        <!-- Bootstrap Navigation Bar Menu -->
<div id="wrapper" class="container">
    <div class="row">
		<!--
        <div class='span12'>
			<?php if(isset($this->breadcrumbs)):?>
				<?php $this->widget('bootstrap.widgets.BootBreadcrumbs', array(
					'links'=>$this->breadcrumbs,
				)); ?>
			<?php endif?>
        </div>
		-->
		
        <div class='span9'>
            <?php
            $flashMessages = Yii::app()->user->getFlashes();
            if ($flashMessages) {
                echo '<div class="flash-messages">';
                foreach ($flashMessages as $key => $message) {
                    echo '<div class="alert alert-' . $key . '">' . "
          <a class='close' data-dismiss='alert'>×</a>
       {$message}
       </div>\n";
                }
                echo '</div>';
            }
            ?>
        </div>
        <div id="main" class="span9" role="main">

            <?php echo $content; ?>
        </div>
        <!-- main content -->
		
        <aside id="sidebar" class='span3'>
        	<?php echo $this->clips['sidebar']; ?>
        </aside>
        <!-- sidebar -->
    </div>
    <!-- row-->
    <footer class="footer">
        <div class="container">
            <div class="gbrfooter"></div>
            <p class='pull-right'>
                Copyright &copy; <?php echo date('Y'); ?> by PikaPiki team. Tugas Besar ARC<br/>
                All Rights Reserved. <?php echo Yii::powered(); ?>
            </div>
        </div>
    </footer>
</div>     <!-- wrapper -->
<?php $this->endContent(); ?>

webapp/protected/views/layouts/grid_bs_sem.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="wrapper" >
    <header id="mainheader" class="ir">
        header
    </header>
    <nav id="main-nav" role="navigation">

    <!-- Bootstrap Navigation Bar Menu -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <!-- Be sure to leave the brand out there if you want it shown -->
                    <a class="brand" href="#">Yii with HTML5 Boilerplate And Semantic Bootstrap.</a>

                    <div class="nav-collapse">
                        <?php $this->widget('zii.widgets.CMenu', array(
                                                                      'items' => array(
                                                                          array('label' => 'Home', 'url' => array('/site/index')),
                                                                          array('label' => 'About', 'url' => array('/site/page', 'view' => 'about')),
                                                                          array('label' => 'Contact', 'url' => array('/site/contact')),
                                                                          array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                                                                          array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
                                                                      ),
                                                                      // 'htmlOptions'=>array('class'=>'main-menu')
                                                                      'htmlOptions' => array('class' => 'nav')
                                                                 )); ?>
                    </div>
                </div>
            </div>
        </div>

            <!-- Bootstrap Navigation Bar Menu -->
    </nav>
    

        <div id='content'>
        <?php $this->widget('zii.widgets.CBreadcrumbs', array(
                                                         'links' => $this->breadcrumbs,
                                                    ));?>
    <?php
$flashMessages = Yii::app()->user->getFlashes();
    if ($flashMessages) {
        echo '<div class="flash-messages">';
        foreach ($flashMessages as $key => $message) {
            echo '<div class="alert alert-' . $key . '">' . "
          <a class='close' data-dismiss='alert'>×</a>
       {$message}
       </div>\n";
        }
        echo '</div>';
    }
    ?>
     
    <div id="main"  role="main">

        <?php echo $content; ?>
    </div>
    <!-- main content -->
    <aside id="sidebar">
        <h2>Sidebar</h2>
        <p>
            <img id="sidebar-img" alt='sidebar' src='http://placehold.it/150x150.png/555555/777777&amp;text=Sidebar'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Praesent sit amet libero eros. Vivamus convallis, libero eu iaculis cursus, diam dui ultrices lorem, a
            ornare quam orci quis libero.
            Morbi interdum cursus odio, sed tincidunt eros tristique sit amet. Mauris sollicitudin diam eget ipsum
            blandit molestie.
            Praesent eu arcu odio. Nulla et adipiscing augue. Donec facilisis ante ac risus dignissim et interdum orci
            porttitor.
            Vivamus posuere blandit venenatis. Proin purus nibh, fringilla id dictum id, eleifend sed diam.
            Pellentesque ac sapien non ipsum blandit tincidunt. Aenean ullamcorper rutrum lacus ac molestie.
            Aliquam sed sem massa. Etiam in rutrum nisl. Morbi lobortis fermentum tellus, vel pharetra purus tincidunt
            venenatis.
            Ut lectus nulla, aliquet a scelerisque vel, cursus congue metus. Proin eget est mi, sed commodo nulla.
            Sed porta ornare nisl at viverra. Morbi quis quam egestas orci pellentesque tempus consectetur congue justo.
        </p>
    </aside><!-- sidebar -->
         <footer>
        <div>
            Copyright &copy; <?php echo date('Y'); ?> by Spiros Kabasakalis.<br/>
                All Rights Reserved.<br/> <?php echo Yii::powered(); ?>Built with <a
                    href="http://html5boilerplate.com/">HTML5 Boilerplate</a> and
                <a href="http://twitter.github.com/bootstrap/index.html">Bootstrap</a>.
        </div>
              <a href="http://www.w3.org/html/logo/" class="span1">
               <img src="http://www.w3.org/html/logo/badge/html5-badge-h-solo.png" width="63" height="64" alt="HTML5 Powered" title="HTML5 Powered">
    </footer>
        </div><!-- row-->

</div>     <!-- wrapper -->

<?php $this->endContent(); ?>

webapp/protected/views/layouts/grid_sg.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="wrapper">

    <header id="mainheader" class="ir">
        header
    </header>
    <nav id="main-nav" role="navigation">

           <!-- Bootstrap Navigation Bar Menu -->

        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <!-- Be sure to leave the brand out there if you want it shown -->
                    <a class="brand" href="#">Yii with HTML5 Boilerplate And Responsive Semantic Grid</a>

                    <div class="nav-collapse">
                        <?php $this->widget('zii.widgets.CMenu', array(
                                                                      'items' => array(
                                                                          array('label' => 'Home', 'url' => array('/site/index')),
                                                                          array('label' => 'About', 'url' => array('/site/page', 'view' => 'about')),
                                                                          array('label' => 'Contact', 'url' => array('/site/contact')),
                                                                          array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                                                                          array('label' => 'Logout (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest)
                                                                      ),
                                                                      // 'htmlOptions'=>array('class'=>'main-menu')
                                                                      'htmlOptions' => array('class' => 'nav')
                                                                 )); ?>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <?php $this->widget('zii.widgets.CBreadcrumbs', array(
                                                         'links' => $this->breadcrumbs,
                                                    ));?>
    <?php
$flashMessages = Yii::app()->user->getFlashes();
    if ($flashMessages) {
        echo '<div class="flash-messages">';
        foreach ($flashMessages as $key => $message) {
            echo '<div class="alert alert-' . $key . '">' . "
          <a class='close' data-dismiss='alert'>×</a>
       {$message}
       </div>\n";
        }
        echo '</div>';
    }
    ?>
    <div id="main" role="main">

        <?php echo $content; ?>
    </div>
    <!-- main content -->
    <aside id="sidebar">
        <h2>Sidebar</h2>
        <p>
            <img id="sidebar-img" alt='sidebar' src='http://placehold.it/150x150.png/555555/777777&amp;text=Sidebar'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Praesent sit amet libero eros. Vivamus convallis, libero eu iaculis cursus, diam dui ultrices lorem, a
            ornare quam orci quis libero.
            Morbi interdum cursus odio, sed tincidunt eros tristique sit amet. Mauris sollicitudin diam eget ipsum
            blandit molestie.
            Praesent eu arcu odio. Nulla et adipiscing augue. Donec facilisis ante ac risus dignissim et interdum orci
            porttitor.
            Vivamus posuere blandit venenatis. Proin purus nibh, fringilla id dictum id, eleifend sed diam.
            Pellentesque ac sapien non ipsum blandit tincidunt. Aenean ullamcorper rutrum lacus ac molestie.
            Aliquam sed sem massa. Etiam in rutrum nisl. Morbi lobortis fermentum tellus, vel pharetra purus tincidunt
            venenatis.
            Ut lectus nulla, aliquet a scelerisque vel, cursus congue metus. Proin eget est mi, sed commodo nulla.
            Sed porta ornare nisl at viverra. Morbi quis quam egestas orci pellentesque tempus consectetur congue justo.
        </p>
    </aside>
    <!-- sidebar -->
    <footer>
         <div>
                Copyright &copy; <?php echo date('Y'); ?> by Spiros Kabasakalis.<br/>
                All Rights Reserved.<br/> <?php echo Yii::powered(); ?>Built with <a
                    href="http://html5boilerplate.com/">HTML5 Boilerplate</a> and
                <a href="http://semantic.gs/">Semantic Grid</a>.
            </div>
         <a href="http://www.w3.org/html/logo/" class="span1">
               <img src="http://www.w3.org/html/logo/badge/html5-badge-h-solo.png" width="63" height="64" alt="HTML5 Powered" title="HTML5 Powered">
    </footer>
</div>     <!-- wrapper -->



<?php $this->endContent(); ?>

webapp/protected/views/layouts/main_OR.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/style.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<?php echo $content; ?>

</div><!-- page -->

</body>
</html>